name: discountzshop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8



  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.17

  # State Management
  #  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
